In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

#IRIS 데이터 로드
iris =  sns.load_dataset('iris') 
X= iris.iloc[:,:4] #학습할데이터
y = iris.iloc[:,-1] #타겟
print(y)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object


In [2]:
scal = StandardScaler() #scaling
X = scal.fit_transform(X)

In [3]:
print(y)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object


In [4]:
# One Versus Rest 구현을 위해 class가 0인것과 아닌것을 구분하기위한 machine class가 1인것과 아닌 것을 구분하기 위한 머신 등을 미리만들어줌
svm_1 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_2 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_3 = SVC(kernel ='rbf', C = 5, gamma = 5)

In [5]:
from sklearn.model_selection import train_test_split #테스트/트레인 데이터로 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)

In [6]:
y_train = pd.get_dummies(y_train) #one hot encoding을 먼저해보자

In [7]:
svm_1.fit(X_train,y_train.iloc[:,0]) # 데이터 클레스가 0인 애인지 아닌지 구분해주는 머신
svm_2.fit(X_train,y_train.iloc[:,1]) # 데이터 클레스가 1인 애인지 아닌지 구분해주는 머신
svm_3.fit(X_train,y_train.iloc[:,2]) # 데이터 클레스가 2인 애인지 아닌지 구분해주는 머신
print(svm_1.predict(X_test)) #데이터 클래스가 0인지 아닌지 구분해주는 애를 통해서 테스트데이터의 클래스가 0인지 0이 아닌인지 예측해보자
print(svm_2.predict(X_test))
print(svm_3.predict(X_test))

print(svm_1.decision_function(X_test)) #decision_function hyperplane과의 거리를 구하는 방법 필요하다면 활용해주세요
print(svm_2.decision_function(X_test))
print(svm_3.decision_function(X_test))

[0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0]
[1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1]
[0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0]
[-1.12470845 -0.86326953 -0.65281099 -0.50248821 -0.76284323 -0.87465573
  1.07709345 -0.99281647  0.47441336 -0.99842743 -0.83989348  0.15633457
  0.32871788 -0.97965464 -0.72385083 -0.92638376  1.28322481 -0.56240455
 -0.72719892 -0.99509775  0.43166724 -0.96451557 -0.82991366 -1.03020581
 -0.75166835  1.13461335  0.39943974 -1.04194106 -0.93376548 -1.06133798]
[ 1.36054602  0.62859488  0.0580828  -0.36987093 -0.25686625 -0.79229874
 -1.03195247 -0.87132049 -0.77957234  0.99327762 -0.73309581 -0.64607768
 -0.71843897 -0.80882458  0.47748663  0.69953462 -1.11879121 -0.1870504
 -0.24458236 -0.99337352 -0.76149141 -0.96812018  0.11310267  1.06892719
 -0.56749692 -1.05639624 -0.74817515 -1.0537858  -0.89721836  1.17126024]
[-1.26277651 -0.77964936 -0.40539105 -0.13070947  0.02643314  0.57365649
 -1.044431

In [8]:
# 부호가 모든 같은 경우가 있는가? 요모두 동점인 경우가 생길것이다.
for i in range(len(X_test)):
    # ~. decision_function을 이용하면 해당 데이터가 하이퍼플레인으로부터 얼마나 떨어져있는 지 거리가 나온다 다음은 그 값의 부호를 이용해
    # 모두가 동점인 경우가 있는지 출력하는 함수 
    if (np.sign(svm_1.decision_function(X_test)[i]) == np.sign(svm_2.decision_function(X_test)[i]))\
    and (np.sign(svm_2.decision_function(X_test)[i]) == np.sign(svm_3.decision_function(X_test)[i])):
        print(i)

3
17
18


In [9]:
decision_list = []
decision_list.append(svm_1.decision_function(X_test))
decision_list.append(svm_2.decision_function(X_test))
decision_list.append(svm_3.decision_function(X_test))
len(decision_list)

3

In [10]:
## Case 1 : One vs Rest SVM을 이부분에 구현해주세요 위 결과들을 이용해서 multi class SVM을 직접 구현해주세요! 하드코딩이 하시기 편할겁니다.

## decision_function 값이 가장 큰 클래스로 분류합니다.
def OneVsRestClassifier(decision_list) :
    count_class = len(decision_list)
    count_data = len(decision_list[0])
    for j in range(count_data) :
        flag = True
        for i in range(count_class-1) :
            if (np.sign(decision_list[i][j])) != (np.sign(decision_list[i+1][j])) :
                flag = False
                break
        if flag :
            decision_value = decision_list[0][j]
            data_class = 0
            for i in range(count_class) :
                if decision_list[i][j] > decision_value:
                    decision_value = decision_list[i][j]
                    data_class = i+1
            print(j, "is classified \'class", data_class, "\'")

In [11]:
OneVsRestClassifier(decision_list)

3 is classified 'class 3 '
17 is classified 'class 2 '
18 is classified 'class 3 '


In [12]:
# Case 2 : One vs One SVM을 이 부분에 구현해주세요. 이것은 선택사항입니다! 

# decision_function 값을 n(n-1)/2 번 비교해서 투표한 다음 가장 많이 투표된 값으로 클래스를 결정합니다.
from scipy import stats
def OneVsOneClassifier(decision_list) :
    data_class = []
    count_class = len(decision_list)
    count_data = len(decision_list[0])
    for j in range(count_data) :
        vote_list = []
        for i in range(count_class):
            for k in range(count_class-1-i):
                if decision_list[i][j] > decision_list[i+k+1][j]:
                    vote_list.append(i+1)
                else :
                    vote_list.append(i+k+2)
        data_class.append(scipy.stats.mode(np.array(vote_list))[0][0])
    print(data_class)
    #return data_class

In [13]:
OneVsOneClassifier(decision_list)

[2, 2, 2, 3, 3, 3, 1, 3, 1, 2, 3, 1, 1, 3, 2, 2, 1, 2, 3, 3, 1, 3, 2, 2, 3, 1, 1, 3, 3, 2]


In [14]:
# 그냥 원래 라이브러리가 제공하는 멀티클래스 SVM과 여러분이 구현한 multiclass SVM결과를 한 번 비교해주세요
from sklearn.model_selection import train_test_split #데이터셋 분리
from sklearn import metrics
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X, y, test_size=0.2, random_state=48)

svm_4 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_4.fit(X_train_2, y_train_2)
y_pred = svm_4.predict(X_test_2)

metrics.accuracy_score(y_test_2,y_pred)

0.8333333333333334